use crate::{consonants::Consonants, vowels::Vowels};

// ConsonantsとVowelsを組み合わせてカタカナを生成
pub fn gen_katakana(consonant: Consonants, vowel: Vowels) -> &'static str {
    match consonant {
        Consonants::K => match vowel {
            Vowels::A => "カ",
            Vowels::I => "キ",
            Vowels::U => "ク",
            Vowels::E => "ケ",
            Vowels::O => "コ",
            _ => "",
        },
        Consonants::Ky => match vowel {
            Vowels::A => "キャ",
            Vowels::I => "キィ",
            Vowels::U => "キュ",
            Vowels::E => "キェ",
            Vowels::O => "キョ",
            _ => "",
        },
        Consonants::G => match vowel {
            Vowels::A => "ガ",
            Vowels::I => "ギ",
            Vowels::U => "グ",
            Vowels::E => "ゲ",
            Vowels::O => "ゴ",
            _ => "",
        },
        Consonants::Gy => match vowel {
            Vowels::A => "ギャ",
            Vowels::I => "ギィ",
            Vowels::U => "ギュ",
            Vowels::E => "ギェ",
            Vowels::O => "ギョ",
            _ => "",
        },
        Consonants::S => match vowel {
            Vowels::A => "サ",
            Vowels::I => "シ",
            Vowels::U => "ス",
            Vowels::E => "セ",
            Vowels::O => "ソ",
            _ => "",
        },
        Consonants::Sy => match vowel {
            Vowels::A => "シャ",
            Vowels::I => "シィ",
            Vowels::U => "シュ",
            Vowels::E => "シェ",
            Vowels::O => "ショ",
            _ => "",
        },
        Consonants::Sh => match vowel {
            Vowels::A => "シャ",
            Vowels::I => "シィ",
            Vowels::U => "シュ",
            Vowels::E => "シェ",
            Vowels::O => "ショ",
            _ => "",
        },
        Consonants::Sg => match vowel {
            Vowels::A => "シャ",
            Vowels::I => "シィ",
            Vowels::U => "シュ",
            Vowels::E => "シェ",
            Vowels::O => "ショ",
            _ => "",
        },
        Consonants::Z => match vowel {
            Vowels::A => "ザ",
            Vowels::I => "ジ",
            Vowels::U => "ズ",
            Vowels::E => "ゼ",
            Vowels::O => "ゾ",
            _ => "",
        },
        Consonants::J => match vowel {
            Vowels::A => "ジャ",
            Vowels::I => "ジ",
            Vowels::U => "ジュ",
            Vowels::E => "ジェ",
            Vowels::O => "ジョ",
            _ => "",
        },
        Consonants::Zy => match vowel {
            Vowels::A => "ジャ",
            Vowels::I => "ジィ",
            Vowels::U => "ジュ",
            Vowels::E => "ジェ",
            Vowels::O => "ジョ",
            _ => "",
        },
        Consonants::Zg => match vowel {
            Vowels::A => "ジャ",
            Vowels::I => "ジィ",
            Vowels::U => "ジュ",
            Vowels::E => "ジェ",
            Vowels::O => "ジョ",
            _ => "",
        },
        Consonants::T => match vowel {
            Vowels::A => "タ",
            Vowels::I => "チ",
            Vowels::U => "ツ",
            Vowels::E => "テ",
            Vowels::O => "ト",
            _ => "",
        },
        Consonants::Ty => match vowel {
            Vowels::A => "チャ",
            Vowels::I => "チィ",
            Vowels::U => "チュ",
            Vowels::E => "チェ",
            Vowels::O => "チョ",
            _ => "",
        },
        Consonants::Th => match vowel {
            Vowels::A => "テャ",
            Vowels::I => "ティ",
            Vowels::U => "テュ",
            Vowels::E => "テェ",
            Vowels::O => "テョ",
            _ => "",
        },
        Consonants::D => match vowel {
            Vowels::A => "ダ",
            Vowels::I => "ヂ",
            Vowels::U => "ヅ",
            Vowels::E => "デ",
            Vowels::O => "ド",
            _ => "",
        },
        Consonants::Dy => match vowel {
            Vowels::A => "ヂャ",
            Vowels::I => "ヂィ",
            Vowels::U => "ヂュ",
            Vowels::E => "ヂェ",
            Vowels::O => "ヂョ",
            _ => "",
        },
        Consonants::Dh => match vowel {
            Vowels::A => "デャ",
            Vowels::I => "ディ",
            Vowels::U => "デュ",
            Vowels::E => "デェ",
            Vowels::O => "デョ",
            _ => "",
        },
        Consonants::N => match vowel {
            Vowels::A => "ナ",
            Vowels::I => "ニ",
            Vowels::U => "ヌ",
            Vowels::E => "ネ",
            Vowels::O => "ノ",
            _ => "",
        },
        Consonants::Ny => match vowel {
            Vowels::A => "ニャ",
            Vowels::I => "ニィ",
            Vowels::U => "ニュ",
            Vowels::E => "ニェ",
            Vowels::O => "ニョ",
            _ => "",
        },
        Consonants::H => match vowel {
            Vowels::A => "ハ",
            Vowels::I => "ヒ",
            Vowels::U => "フ",
            Vowels::E => "ヘ",
            Vowels::O => "ホ",
            _ => "",
        },
        Consonants::Hy => match vowel {
            Vowels::A => "ヒャ",
            Vowels::I => "ヒィ",
            Vowels::U => "ヒュ",
            Vowels::E => "ヒェ",
            Vowels::O => "ヒョ",
            _ => "",
        },
        Consonants::Hg => match vowel {
            Vowels::A => "ヒャ",
            Vowels::I => "ヒィ",
            Vowels::U => "ヒュ",
            Vowels::E => "ヒェ",
            Vowels::O => "ヒョ",
            _ => "",
        },
        Consonants::F => match vowel {
            Vowels::A => "ファ",
            Vowels::I => "フィ",
            Vowels::U => "フ",
            Vowels::E => "フェ",
            Vowels::O => "フォ",
            _ => "",
        },
        Consonants::Fy => match vowel {
            Vowels::A => "フャ",
            Vowels::I => "フィ",
            Vowels::U => "フュ",
            Vowels::E => "フェ",
            Vowels::O => "フョ",
            _ => "",
        },
        Consonants::B => match vowel {
            Vowels::A => "バ",
            Vowels::I => "ビ",
            Vowels::U => "ブ",
            Vowels::E => "ベ",
            Vowels::O => "ボ",
            _ => "",
        },
        Consonants::By => match vowel {
            Vowels::A => "ビャ",
            Vowels::I => "ビィ",
            Vowels::U => "ビュ",
            Vowels::E => "ビェ",
            Vowels::O => "ビョ",
            _ => "",
        },
        Consonants::Bg => match vowel {
            Vowels::A => "ビャ",
            Vowels::I => "ビィ",
            Vowels::U => "ビュ",
            Vowels::E => "ビェ",
            Vowels::O => "ビョ",
            _ => "",
        },
        Consonants::P => match vowel {
            Vowels::A => "パ",
            Vowels::I => "ピ",
            Vowels::U => "プ",
            Vowels::E => "ペ",
            Vowels::O => "ポ",
            _ => "",
        },
        Consonants::Py => match vowel {
            Vowels::A => "ピャ",
            Vowels::I => "ピィ",
            Vowels::U => "ピュ",
            Vowels::E => "ピェ",
            Vowels::O => "ピョ",
            _ => "",
        },
        Consonants::Pg => match vowel {
            Vowels::A => "ピャ",
            Vowels::I => "ピィ",
            Vowels::U => "ピュ",
            Vowels::E => "ピェ",
            Vowels::O => "ピョ",
            _ => "",
        },
        Consonants::M => match vowel {
            Vowels::A => "マ",
            Vowels::I => "ミ",
            Vowels::U => "ム",
            Vowels::E => "メ",
            Vowels::O => "モ",
            _ => "",
        },
        Consonants::My => match vowel {
            Vowels::A => "ミャ",
            Vowels::I => "ミィ",
            Vowels::U => "ミュ",
            Vowels::E => "ミェ",
            Vowels::O => "ミョ",
            _ => "",
        },
        Consonants::Y => match vowel {
            Vowels::A => "ヤ",
            Vowels::I => "イ",
            Vowels::U => "ユ",
            Vowels::E => "イェ",
            Vowels::O => "ヨ",
            _ => "",
        },
        Consonants::R => match vowel {
            Vowels::A => "ラ",
            Vowels::I => "リ",
            Vowels::U => "ル",
            Vowels::E => "レ",
            Vowels::O => "ロ",
            _ => "",
        },
        Consonants::Ry => match vowel {
            Vowels::A => "リャ",
            Vowels::I => "リィ",
            Vowels::U => "リュ",
            Vowels::E => "リェ",
            Vowels::O => "リョ",
            _ => "",
        },
        Consonants::W => match vowel {
            Vowels::A => "ワ",
            Vowels::I => "ウィ",
            Vowels::U => "ウ",
            Vowels::E => "ウェ",
            Vowels::O => "ヲ",
            _ => "",
        },
        Consonants::Wh => match vowel {
            Vowels::A => "ウア",
            Vowels::I => "ウィ",
            Vowels::U => "ウ",
            Vowels::E => "ウェ",
            Vowels::O => "ウォ",
            _ => "",
        },
        Consonants::V => match vowel {
            Vowels::A => "ヴァ",
            Vowels::I => "ヴィ",
            Vowels::U => "ヴ",
            Vowels::E => "ヴェ",
            Vowels::O => "ヴォ",
            _ => "",
        },
    }
}
