use crate::{consonants::Consonants, vowels::Vowels};

// ConsonantsとVowelsを組み合わせて半角カタカナを生成
pub fn gen_half_katakana(consonant: Consonants, vowel: Vowels) -> &'static str {
    match consonant {
        Consonants::K => match vowel {
            Vowels::A => "ｶ",
            Vowels::I => "ｷ",
            Vowels::U => "ｸ",
            Vowels::E => "ｹ",
            Vowels::O => "ｺ",
            _ => "",
        },
        Consonants::Ky => match vowel {
            Vowels::A => "ｷｬ",
            Vowels::I => "ｷｨ",
            Vowels::U => "ｷｭ",
            Vowels::E => "ｷｪ",
            Vowels::O => "ｷｮ",
            _ => "",
        },
        Consonants::G => match vowel {
            Vowels::A => "ｶﾞ",
            Vowels::I => "ｷﾞ",
            Vowels::U => "ｸﾞ",
            Vowels::E => "ｹﾞ",
            Vowels::O => "ｺﾞ",
            _ => "",
        },
        Consonants::Gy => match vowel {
            Vowels::A => "ｷﾞｬ",
            Vowels::I => "ｷﾞｨ",
            Vowels::U => "ｷﾞｭ",
            Vowels::E => "ｷﾞｪ",
            Vowels::O => "ｷﾞｮ",
            _ => "",
        },
        Consonants::S => match vowel {
            Vowels::A => "ｻ",
            Vowels::I => "ｼ",
            Vowels::U => "ｽ",
            Vowels::E => "ｾ",
            Vowels::O => "ｿ",
            _ => "",
        },
        Consonants::Sy => match vowel {
            Vowels::A => "ｼｬ",
            Vowels::I => "ｼｨ",
            Vowels::U => "ｼｭ",
            Vowels::E => "ｼｪ",
            Vowels::O => "ｼｮ",
            _ => "",
        },
        Consonants::Sh => match vowel {
            Vowels::A => "ｼｬ",
            Vowels::I => "ｼｨ",
            Vowels::U => "ｼｭ",
            Vowels::E => "ｼｪ",
            Vowels::O => "ｼｮ",
            _ => "",
        },
        Consonants::Sg => match vowel {
            Vowels::A => "ｼｬ",
            Vowels::I => "ｼｨ",
            Vowels::U => "ｼｭ",
            Vowels::E => "ｼｪ",
            Vowels::O => "ｼｮ",
            _ => "",
        },
        Consonants::Z => match vowel {
            Vowels::A => "ｻﾞ",
            Vowels::I => "ｼﾞ",
            Vowels::U => "ｽﾞ",
            Vowels::E => "ｾﾞ",
            Vowels::O => "ｿﾞ",
            _ => "",
        },
        Consonants::J => match vowel {
            Vowels::A => "ｼﾞｬ",
            Vowels::I => "ｼﾞ",
            Vowels::U => "ｼﾞｭ",
            Vowels::E => "ｼﾞｪ",
            Vowels::O => "ｼﾞｮ",
            _ => "",
        },
        Consonants::Zy => match vowel {
            Vowels::A => "ｼﾞｬ",
            Vowels::I => "ｼﾞｨ",
            Vowels::U => "ｼﾞｭ",
            Vowels::E => "ｼﾞｪ",
            Vowels::O => "ｼﾞｮ",
            _ => "",
        },
        Consonants::Zg => match vowel {
            Vowels::A => "ｼﾞｬ",
            Vowels::I => "ｼﾞｨ",
            Vowels::U => "ｼﾞｭ",
            Vowels::E => "ｼﾞｪ",
            Vowels::O => "ｼﾞｮ",
            _ => "",
        },
        Consonants::T => match vowel {
            Vowels::A => "ﾀﾀ",
            Vowels::I => "ﾁ",
            Vowels::U => "ﾂ",
            Vowels::E => "ﾃ",
            Vowels::O => "ﾄ",
            _ => "",
        },
        Consonants::Ty => match vowel {
            Vowels::A => "ﾁｬ",
            Vowels::I => "ﾁｨ",
            Vowels::U => "ﾁｭ",
            Vowels::E => "ﾁｪ",
            Vowels::O => "ﾁｮ",
            _ => "",
        },
        Consonants::Th => match vowel {
            Vowels::A => "ﾃｬ",
            Vowels::I => "ﾃｨ",
            Vowels::U => "ﾃｭ",
            Vowels::E => "ﾃｪ",
            Vowels::O => "ﾃﾖ",
            _ => "",
        },
        Consonants::D => match vowel {
            Vowels::A => "ﾀﾞ",
            Vowels::I => "ﾁﾞ",
            Vowels::U => "ﾂﾞ",
            Vowels::E => "ﾃﾞ",
            Vowels::O => "ﾄﾞ",
            _ => "",
        },
        Consonants::Dy => match vowel {
            Vowels::A => "ﾁﾞｬ",
            Vowels::I => "ﾁﾞｨ",
            Vowels::U => "ﾁﾞｭ",
            Vowels::E => "ﾁﾞｪ",
            Vowels::O => "ﾁﾞｮ",
            _ => "",
        },
        Consonants::Dh => match vowel {
            Vowels::A => "ﾃﾞｬ",
            Vowels::I => "ﾃﾞｨ",
            Vowels::U => "ﾃﾞｭ",
            Vowels::E => "ﾃﾞｪ",
            Vowels::O => "ﾃﾞｮ",
            _ => "",
        },
        Consonants::N => match vowel {
            Vowels::A => "ﾅ",
            Vowels::I => "ﾆ",
            Vowels::U => "ﾇ",
            Vowels::E => "ﾈ",
            Vowels::O => "ﾉ",
            _ => "",
        },
        Consonants::Ny => match vowel {
            Vowels::A => "ﾆｬ",
            Vowels::I => "ﾆｨ",
            Vowels::U => "ﾆｭ",
            Vowels::E => "ﾆｪ",
            Vowels::O => "ﾆｮ",
            _ => "",
        },
        Consonants::H => match vowel {
            Vowels::A => "ﾊ",
            Vowels::I => "ﾋ",
            Vowels::U => "ﾌ",
            Vowels::E => "ﾍ",
            Vowels::O => "ﾎ",
            _ => "",
        },
        Consonants::Hy => match vowel {
            Vowels::A => "ﾋｬ",
            Vowels::I => "ﾋｨ",
            Vowels::U => "ﾋｭ",
            Vowels::E => "ﾋｪ",
            Vowels::O => "ﾋｮ",
            _ => "",
        },
        Consonants::Hg => match vowel {
            Vowels::A => "ﾋｬ",
            Vowels::I => "ﾋｨ",
            Vowels::U => "ﾋｭ",
            Vowels::E => "ﾋｪ",
            Vowels::O => "ﾋｮ",
            _ => "",
        },
        Consonants::F => match vowel {
            Vowels::A => "ﾌｧ",
            Vowels::I => "ﾌｨ",
            Vowels::U => "ﾌ",
            Vowels::E => "ﾌｪ",
            Vowels::O => "ﾌｫ",
            _ => "",
        },
        Consonants::Fy => match vowel {
            Vowels::A => "ﾌｬ",
            Vowels::I => "ﾌｨ",
            Vowels::U => "ﾌﾕ",
            Vowels::E => "ﾌｪ",
            Vowels::O => "ﾌｮ",
            _ => "",
        },
        Consonants::B => match vowel {
            Vowels::A => "ﾊﾞ",
            Vowels::I => "ﾋﾞ",
            Vowels::U => "ﾌﾞ",
            Vowels::E => "ﾍﾞ",
            Vowels::O => "ﾎﾞ",
            _ => "",
        },
        Consonants::By => match vowel {
            Vowels::A => "ﾋﾞｬ",
            Vowels::I => "ﾋﾞｨ",
            Vowels::U => "ﾋﾞｭ",
            Vowels::E => "ﾋﾞｪ",
            Vowels::O => "ﾋﾞｮ",
            _ => "",
        },
        Consonants::Bg => match vowel {
            Vowels::A => "ﾋﾞｬ",
            Vowels::I => "ﾋﾞｨ",
            Vowels::U => "ﾋﾞｭ",
            Vowels::E => "ﾋﾞｪ",
            Vowels::O => "ﾋﾞｮ",
            _ => "",
        },
        Consonants::P => match vowel {
            Vowels::A => "ﾊﾟ",
            Vowels::I => "ﾋﾟ",
            Vowels::U => "ﾌﾟ",
            Vowels::E => "ﾍﾟ",
            Vowels::O => "ﾎﾟ",
            _ => "",
        },
        Consonants::Py => match vowel {
            Vowels::A => "ﾋﾟｬ",
            Vowels::I => "ﾋﾟｨ",
            Vowels::U => "ﾋﾟｭ",
            Vowels::E => "ﾋﾟｪ",
            Vowels::O => "ﾋﾟｮ",
            _ => "",
        },
        Consonants::Pg => match vowel {
            Vowels::A => "ﾋﾟｬ",
            Vowels::I => "ﾋﾟｨ",
            Vowels::U => "ﾋﾟｭ",
            Vowels::E => "ﾋﾟｪ",
            Vowels::O => "ﾋﾟｮ",
            _ => "",
        },
        Consonants::M => match vowel {
            Vowels::A => "ﾏ",
            Vowels::I => "ﾐ",
            Vowels::U => "ﾑ",
            Vowels::E => "ﾒ",
            Vowels::O => "ﾓ",
            _ => "",
        },
        Consonants::My => match vowel {
            Vowels::A => "ﾐｬ",
            Vowels::I => "ﾐｨ",
            Vowels::U => "ﾐｭ",
            Vowels::E => "ﾐｪ",
            Vowels::O => "ﾐｮ ",
            _ => "",
        },
        Consonants::Y => match vowel {
            Vowels::A => "ﾔ",
            Vowels::I => "ｲ",
            Vowels::U => "ﾕ",
            Vowels::E => "ｲｪ",
            Vowels::O => "ﾖ",
            _ => "",
        },
        Consonants::R => match vowel {
            Vowels::A => "ﾗ",
            Vowels::I => "ﾘ",
            Vowels::U => "ﾙ",
            Vowels::E => "ﾚ",
            Vowels::O => "ﾛ",
            _ => "",
        },
        Consonants::Ry => match vowel {
            Vowels::A => "ﾘｬ",
            Vowels::I => "ﾘｨ",
            Vowels::U => "ﾘｭ",
            Vowels::E => "ﾘｪ",
            Vowels::O => "ﾘｮ",
            _ => "",
        },
        Consonants::W => match vowel {
            Vowels::A => "ﾜ",
            Vowels::I => "ｳｨ",
            Vowels::U => "ｳ",
            Vowels::E => "ｳｪ",
            Vowels::O => "ｦ",
            _ => "",
        },
        Consonants::Wh => match vowel {
            Vowels::A => "ｳｧ",
            Vowels::I => "ｳｨ",
            Vowels::U => "ｳ",
            Vowels::E => "ｳｪ",
            Vowels::O => "ｳｫ",
            _ => "",
        },
        Consonants::V => match vowel {
            Vowels::A => "ｳﾞｧ",
            Vowels::I => "ｳﾞｨ",
            Vowels::U => "ｳﾞ",
            Vowels::E => "ｳﾞｪ",
            Vowels::O => "ｳﾞｫ",
            _ => "",
        },
    }
}
